def thermal_inertia(k: float, p: float, c: float) -> float: ...
def conductivity(ti: float, p: float, c: float) -> float: ...
def diffusivity(k: float, p: float, c: float) -> float: ...
def skin_depth_1(d: float, p: float) -> float: ...
def skin_depth_2pi(d: float, p: float) -> float: ...

class Properties:
    albedo: float
    emissivity: float
    density: float
    heat_capacity: float
    thermal_inertia: float
    conductivity: float
    diffusivity: float

    def __init__(self) -> None: ...
    def compute_thermal_inertia(self) -> None: ...
    def compute_conductivity(self) -> None: ...
    def compute_diffusivity(self) -> None: ...
    def compute_conductivity_diffusivity(self) -> None: ...

DIDYMOS: Properties
DIMORPHOS: Properties
MOON: Properties
PHOBOS: Properties
DEIMOS: Properties
