import numpy

def cosine_angle_vectors(u: numpy.array, v: numpy.array) -> float: ...
def cosine_incidence(sundir: numpy.array, normal: numpy.array) -> float: ...
def flattening_radius(radii: numpy.array) -> float: ...

def trapez(y: numpy.array, x: numpy.array) -> float: ...
def simpson_1_3(y: numpy.array, x: numpy.array) -> float: ...
def simpson_3_8(y: numpy.array, x: numpy.array) -> float: ...
def boole(y: numpy.array, x: numpy.array) -> float: ...