# from typing import Tuple

# import numpy

# def load_image(path: str) -> Tuple[Tuple[int, int], bytes]: ...
# def normal_facet(ab: numpy.array, ac: numpy.array) -> numpy.array: ...
# def area_facet(ab: numpy.array, ac: numpy.array) -> float: ...
# def is_point_in_or_on(p1: numpy.array, p2: numpy.numpy.array, a: numpy.array, b: numpy.array) -> bool: ...
# def is_point_in_or_on_triangle(p: numpy.array, a: numpy.array, b: numpy.array, c: numpy.array) -> bool: ...
# def is_facing_plane(u: numpy.array, n: numpy.array) -> bool: ...
# def is_not_parallel_to_plane(u: numpy.array, n: numpy.array) -> bool: ...
# def intersect_plane(p: numpy.array, u: numpy.array, a: numpy.array, n: numpy.array) -> numpy.array | None: ...
# def intersect_triangle(p: numpy.array, u: numpy.array, a: numpy.array, b: numpy.array, c: numpy.array, n: numpy.array) -> numpy.array | None: ...
# def intersect_triangle_moller_trumbore(p: numpy.array, u: numpy.array, a: numpy.array, b: numpy.array, c: numpy.array) -> numpy.array | None: ...
# def view_factor_scalar_with_area(area_b: float, angle_at_a: float, angle_at_b: float, distance_a2b: float) -> float: ...
# def view_factor_scalar(angle_at_a: float, angle_at_b: float, distance_a2b: float) -> float: ...
# def largest_slope_angle_sphere(S: float) -> float: ...
# def curvature_diameter_sphere(S: float) -> float: ...
# def curvature_radius(r: float, d: float) -> float: ...
# def curvature_diameter_from_radius(d: float, R: float) -> float: ...
# def z_in_crater(x: float, y: float, r: float, d: float) -> float: ...
# def rms_slope(f: float, g: float) -> float: ...
# def rms_slope_hemisphere(f: float) -> float: ...
# def rms_slope_terrain(theta: numpy.array, a: numpy.array) -> float: ...
# def distribution_slope_angles(theta: float, a: float, b: float) -> float: ...

# def intersect_mesh(mesh: "Mesh", p: numpy.array, u: numpy.array, exit_first: bool = False) -> Tuple[int, numpy.array] | None: ...
# def view_factor_facets(face_a: "Facet", face_b: "Facet", trans_b2a: numpy.array) -> float: ...