def thermal_inertia(k: float, p: float, c: float) -> float: ...
def conductivity(ti: float, p: float, c: float) -> float: ...
def diffusivity(k: float, p: float, c: float) -> float: ...
def skin_depth_1(d: float, p: float) -> float: ...
def skin_depth_2pi(d: float, p: float) -> float: ...
